---
title: "MSDS 411 Project AMES Housing"
author: "Robin Singh"
date: "8/17/2021"
output: html_document
---

```{r}
mydata <- read.csv(file="ames_housing_data.csv",head=TRUE,sep=",")
mydata
```
```{r}
mydata$TotalFloorSF <- mydata$FirstFlrSF + mydata$SecondFlrSF
mydata$HouseAge <- mydata$YrSold - mydata$YearBuilt
mydata$QualityIndex <- mydata$OverallQual * mydata$OverallCond
mydata$logSalePrice <- log(mydata$SalePrice)
mydata$price_sqft <- mydata$SalePrice/mydata$TotalFloorSF
summary(mydata$price_sqft)
hist(mydata$price_sqft)
subdata <- subset(mydata, select=c("TotalFloorSF","HouseAge","QualityIndex",
                                  "price_sqft", "SalePrice","LotArea",
                                  "BsmtFinSF1","Neighborhood","HouseStyle",
                                  "LotShape","OverallQual","logSalePrice",
                                  "TotalBsmtSF","HouseStyle","Zoning","LotShape","SaleCondition","Functional", "LotArea","SubClass","LotFrontage","OverallCond", "YearBuilt", "ExterQual", "ExterCond", "FirstFlrSF", "SecondFlrSF", "BedroomAbvGr", "TotRmsAbvGrd", "GrLivArea", "MiscVal", "YearRemodel"))



subdata
```

```{r}
subdatnum <- subset(mydata, select=c("TotalFloorSF","HouseAge","QualityIndex",
                                     "SalePrice","LotArea","OverallQual"))

require(lattice)
pairs(subdatnum, pch = 21)

require(corrplot)
mcor <- cor(subdatnum)
corrplot(mcor, method="shade", shade.col=NA, tl.col="black",tl.cex=0.5)
```
Overall quality and SalePrice seems to have a bit of a linear relationship, as well as quality index but that is to be expected. 

SalePrice and TotalFLoorSF seems to have a slight linear relationship.

logSalePrice and HouseAge seem to have an opposite linear coordination. 

```{r}
library(ggplot2)
ggplot(subdata, aes(x=TotalFloorSF, y=QualityIndex)) + 
  geom_point(color="blue", shape=1) +
  ggtitle("Scatter Plot of Total Floor SF vs QualityIndex") +
  theme(plot.title=element_text(lineheight=0.8, face="bold", hjust=0.5))

ggplot(subdata, aes(x=TotalFloorSF, y=HouseAge)) + 
  geom_point(color="blue", shape=1) +
  ggtitle("Scatter Plot of Total Floor SF vs HouseAge") +
  theme(plot.title=element_text(lineheight=0.8, face="bold", hjust=0.5))

ggplot(subdata, aes(x=TotalFloorSF, y=SalePrice)) + 
  geom_point(color="blue", shape=1) +
  ggtitle("Scatter Plot of Total Floor SF vs QualityIndex") +
  theme(plot.title=element_text(lineheight=0.8, face="bold", hjust=0.5))

ggplot(subdata, aes(x=SalePrice, y=QualityIndex)) + 
  geom_point(color="blue", shape=1) +
  ggtitle("Scatter Plot of Total Floor SF vs HouseAge") +
  theme(plot.title=element_text(lineheight=0.8, face="bold", hjust=0.5))
```

```{r}

model1=lm(SalePrice~., data=subdata)
summary(model1)
model1
```



```{r}
model2=lm(SalePrice~TotalFloorSF+HouseAge+OverallQual+LotArea+MiscVal, data=subdata)
summary(model2)
model2
```




```{r}


model3=lm(SalePrice~TotalFloorSF+HouseAge+OverallQual+LotArea+MiscVal, data=subdata)
summary(model3)
model3
```
```{r}
library('fastDummies')
subdata <- dummy_cols(subdata, select_columns = c('Neighborhood','Zoning'),
           remove_selected_columns = TRUE)
subdata

```


```{r}
num_cols <- unlist(lapply(subdata, is.numeric))

subdata <- subdata[ ,num_cols]
model4=lm(SalePrice~., data=subdata)
summary(model4)
model4
```
```{r}
subdata=na.omit(subdata)
subdata
subdata= subdata[,!(names(subdata) %in% c('LotArea.1', 'SecondFlrSF' ))]
```


```{r}
corrmatrix <- rcorr(as.matrix(subdata))
corrmatrix
```
```{r}
is.matrix(corrmatrix$r)
corrmatrix=corrmatrix$r
isSymmetric(corrmatrix)
```

```{r}
library(corrplot)
corrplot(corrmatrix)
```
```{r}
library(psych)
fa(corrmatrix, nfactors=8) 
factors_data <- factanal(covmat=corrmatrix, n.obs=2439, factors=3, rotation='varimax');

```
```{r}
fa.parallel(subdata, 
            n.obs=2439, 
            fa="both", 
            n.iter=100,
            fm="ml",
            show.legend=TRUE, main="Scree plot with parallel analysis")
```

```{r}
eigen(corrmatrix)
```

```{r}
factors_data <- fa(r = corrmatrix, nfactors = 5)

#factors_data <- factanal(covmat=corrmatrix, n.obs=2439, factors=4, rotation='varimax', fm='ml');

factors_data
```
```{r}
factors_data <- factanal(covmat=corrmatrix, n.obs=2439, factors=4, rotation='promax',fm='ml');
factors_data
```

```{r}
factors_data <- fa(r = corrmatrix, nfactors = 6)

#factors_data <- factanal(covmat=corrmatrix, n.obs=2439, factors=4, rotation='varimax', fm='ml');

factors_data
```
```{r}
###########################
# Helper functions
###########################

# find the graph node number by the coordinates
find_node_by_coordinates <- function(x, y, grid_width) {
 return(((y * grid_width) + x) - grid_width)
}

# return the number of observations represented by each node
get_node_counts <- function(x) {
 df <- data.frame(node = x)
 counts <- df %>%
   group_by(node) %>%
   summarize(observations = n())
}

# guideline for grid size = 5 * sqrt(N)
# where N is the number of observations in the data set
find_grid_size <- function(N) {
 return(floor(sqrt(sqrt(N) * 5)))
}

# Shane Lynn 14-01-2014 used to define the palette
coolBlueHotRed <- function(n, alpha = 1) {
 rainbow(n, end=4/6, alpha=alpha)[n:1]
}
```













